# Site settings
title: Memex updates
email: grohit@cmu.edu
description: > # this means to ignore newlines until "baseurl:"
  Updates on the memex project
baseurl: "/~rohit/projects/002_memex/weblog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  rohitgirdhar

# Build settings
markdown: redcarpet
